config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  
  devise_for :users

  root to: "homes#top"

  patch 'users/update_user_name', to: 'users#update_user_name', as: :update_user_name
  patch 'users/update_user_image', to: 'users#update_user_image', as: :update_user_image
  
  namespace :admin do
    resources :users do
      member do
        post :reactivate
        post :deactivate
        post :freeze
      end
    end
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      post :deactivate
      get :following, :followers
    end
  end

  get "search" => "searches#search"
  
  resources :posts, only: [:new, :create, :index, :show, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  
  resources :favorites, only: [:index]
  
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Devise modules
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  # Associations
  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  # Profile image method
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # Search method
  def self.looks(search, word)
    if search == "perfect_match"
      where("name LIKE ?", word)
    elsif search == "partial_match"
      where("name LIKE ?", "%#{word}%")
    else
      all
    end
  end

  # Follow and unfollow methods
  def following?(other_user)
    active_relationships.exists?(followed_id: other_user.id)
  end

  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  # User status management
  enum status: { active: 0, deactivated: 1, frozen: 2 }
  scope :active_users, -> { where(status: :active) }

  def status_i18n
    I18n.t("activerecord.attributes.user.statuses.#{status}")
  end

  def deactivate
    current_user.deactivate! # アカウントを非有効化
    sign_out(current_user)     # 非有効化後にログアウト
    redirect_to root_path, notice: 'アカウントが非有効化されました。'
  end

  def deactivate!
    update(status: :deactivated)
  end

  def freeze!
    update(status: :frozen)
  end

  def reactivate!
    update(status: :active)
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end
  
  def edit
  end

  def show
    @user = User.find(params[:id])
  end

  # 退会メソッド
  def deactivate
    user = User.find(params[:id])
    user.deactivate!
    redirect_to admin_users_path, notice: "ユーザーを退会状態にしました。"
  end
  # 凍結メソッド
  def freeze
    user = User.find(params[:id])
    user.freeze!
    redirect_to admin_users_path, notice: "ユーザーを凍結しました。"
  end
  # アクティブに戻すメソッド
  def reactivate
    user = User.find(params[:id])
    user.reactivate!
    redirect_to admin_users_path, notice: "ユーザーをアクティブに戻しました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc).page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def update_user_name
    @user = current_user
    if @user.update(user_name_params)
      redirect_to user_path(@user), notice: 'ユーザー名が更新されました'
    else
      render :edit
    end
  end

  def update_user_image
    @user = current_user
    if @user.update(user_image_params)
      redirect_to user_path(@user), notice: 'プロフィール画像が更新されました'
    else
      render :edit
    end
  end
  
  def following
    @title = "フォロー"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "フォローワー"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end
  
  def deactivate
    current_user.deactivate!
    redirect_to root_path, notice: 'アカウントが非有効化されました。'
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :header_image)
  end
  
  def user_name_params
    params.require(:user).permit(:name)
  end

  def user_image_params
    params.require(:user).permit(:profile_image)
  end
  
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<ul class="list-group">
  <% @users.each do |user| %>
    <li class="list-group-item d-flex align-items-center mb-3">
      <%= link_to user_path(user), class: "d-flex align-items-center w-100" do %>
        <%= image_tag user.get_profile_image(100, 100), class: "rounded-circle me-3", alt: "#{user.name}'s profile picture" %>
        <div>
          <span class="text-dark fw-bold"><%= user.name %></span>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="profile-wrap">
  <div class="container mt-4">
    <div class="row justify-content-center">
      <div class="col-md-4 text-center">
        <%= image_tag @user.get_profile_image(100, 100), class: "img-fluid rounded-circle" %>
      </div>
      <div class="col-md-4 text-center">
        <h1><%= @user.name %></h1>

        <div>
          <%= link_to "#{@user.following.count} フォロー", following_user_path(@user), class: "text-dark" %> |
          <%= link_to "#{@user.followers.count} フォロワー", followers_user_path(@user), class: "text-dark" %>
        </div>
        <% if user_signed_in? %>
          <% if @user == current_user %>
            <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
          <% else %>
            <% if current_user.following?(@user) %>
              <%= button_to "フォロー解除", relationship_path(current_user.active_relationships.find_by(followed_id: @user.id)), method: :delete, class: "btn btn-danger" %>
            <% else %>
              <%= button_to "フォロー", relationships_path(followed_id: @user.id), method: :post, class: "btn btn-primary" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container mt-4">
    <%= render 'posts/list', posts: @posts %>
  </div>
</div>

app/views/users/show_follow.html.erb
<h1><%= @title %></h1>
<ul class="users">
  <%= render @users %>
</ul>