config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  
  devise_for :users

  root to: "homes#top"

  patch 'users/update_user_name', to: 'users#update_user_name', as: :update_user_name
  patch 'users/update_user_image', to: 'users#update_user_image', as: :update_user_image
  
  namespace :admin do
    resources :users do
      member do
        post :reactivate
        post :deactivate
        post :freeze
      end
    end
  end

  resources :users, only: [:show, :edit, :update] do
    member do
      post :deactivate
      get :following, :followers
    end
  end

  get "search" => "searches#search"
  
  resources :posts, only: [:new, :create, :index, :show, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  
  resources :favorites, only: [:index]
  
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffee Break</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/29d9f0d25f.js" crossorigin="anonymous"></script>
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <% if user_signed_in? %>
        <%= link_to "Coffee Break", posts_path, class: "navbar-brand" %>
        <% else %>
         <%= link_to "Coffee Break", '/', class: "navbar-brand" %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "投稿", new_post_path, class: "fa-regular fa-paper-plane nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿一覧", posts_path, class: "fa-solid fa-mug-saucer nav-link text-light" %>
              </li>
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "いいね", favorites_path, class: "fa-solid fa-heart nav-link text-light" %>
                </li>
              <% end %>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "fa-solid fa-right-from-bracket nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to user_path(current_user), class: "nav-link text-light d-flex align-items-center" do %>
                  <%= image_tag current_user.get_profile_image(20, 20), class: "rounded-circle me-2" %>
                <% end %>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "管理者用ユーザー一覧", admin_users_path, class: "fa-solid fa-users nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "fa-solid fa-right-from-bracket nav-link text-light" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Home", '/', class: "fa-solid fa-house nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿一覧", posts_path, class: "fa-solid fa-mug-saucer nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "サインアップ", new_user_registration_path, class: "fa-solid fa-user-plus nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: "fa-solid fa-right-to-bracket nav-link text-light" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main>
    <%= yield %>
  </main>
</body>
</html>